name: $(Date:yyyyMMdd).$(Rev:r).$(Build.BuildId)

trigger: 
  branches:
    include:
      - master
pr: none

variables:
- name: release_name
  value: zeebe


stages:

- stage: BUILD
  displayName: 'Package helm charts'
  pool:
    #vmImage: windows-2019
    name: agentvmss
  jobs:
  - job: BUILD
    displayName: 'Package helm charts'
    steps:
    - task: HelmDeploy@0
      displayName: 'Package zeebe cluster helm chart'
      inputs:
        command: package
        chartPath: zeebe-cluster-helm
        destination: $(Build.ArtifactStagingDirectory)-cluster
        updatedependency: true
        save: false

    - task: HelmDeploy@0
      displayName: 'Package zeebe operator helm chart'
      inputs:
        command: package
        chartPath: zeebe-operate-helm
        destination: $(Build.ArtifactStagingDirectory)-operator
        updatedependency: true
        save: false

    - task: CopyFiles@2
      displayName: Copy CI files to artifact directory
      inputs:
        SourceFolder: zeebe-operate-helm/ci
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)-operator'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop-cluster'
      inputs:
        PathtoPublish: $(Build.ArtifactStagingDirectory)-cluster
        ArtifactName: drop-cluster

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop-operator'
      inputs:
           PathtoPublish: $(Build.ArtifactStagingDirectory)-operator
           ArtifactName: drop-operator


# - stage: Zeebe_RELEASE
#   displayName: 'Deploy zeebe cluster & operator in Test'
#   pool:
#     vmImage: windows-2019
#   jobs:
#   - deployment: DeployZeebeTest
#     displayName: 'Deploy zeebe cluster & operator'
#     environment: 
#       name: 'zeebe'               
#       resourceName: 'zeebe'        
#       resourceType: Kubernetes
#     strategy:
#       runOnce:
#         deploy:
#           steps:
#           # - task: HelmDeploy@0
#           #   displayName: 'Deploy zeebe cluster'
#           #   inputs:
#           #     namespace: 'zeebe'
#           #     command: upgrade
#           #     arguments: '--timeout 900s'
#           #     chartType: FilePath
#           #     chartPath: '$(Agent.BuildDirectory)/drop-cluster/zeebe-cluster-helm-0.1.0.tgz'
#           #     releaseName: '$(release_name)-cluster' 

#           - task: HelmDeploy@0
#             displayName: 'Deploy zeebe operator'
#             condition: succeededOrFailed()
#             inputs:
#               namespace: 'default'
#               command: upgrade
#               chartType: FilePath
#               chartPath: '$(Agent.BuildDirectory)/drop-operator/zeebe-operate-0.1.0.tgz'
#               releaseName: '$(release_name)-operator'
#               valueFile: '$(Agent.BuildDirectory)/drop-operator/values.zeebe.yaml'

- stage: Default_RELEASE
  displayName: 'Deploy zeebe cluster & operator in UAT'
  condition: succeeded('BUILD')
  pool:
    #vmImage: windows-2019
    name: agentvmss
  jobs:
  - deployment: DeployZeebeUAT
    displayName: 'Deploy zeebe cluster & operator'
    environment: 
      name: 'trigger'               
      resourceName: 'default'        
      resourceType: Kubernetes
    strategy:
      runOnce:
        deploy:
          steps:
          # - task: HelmDeploy@0
          #   displayName: 'Deploy zeebe cluster'
          #   inputs:
          #     namespace: 'default'
          #     command: upgrade
          #     arguments: '--timeout 600s'
          #     chartType: FilePath
          #     chartPath: '$(Agent.BuildDirectory)/drop-cluster/zeebe-cluster-helm-0.1.0.tgz'
          #     releaseName: '$(release_name)-cluster' 

          - task: HelmDeploy@0
            displayName: 'Deploy zeebe operator'
            condition: succeededOrFailed()
            inputs:
              namespace: 'default'
              command: upgrade
              chartType: FilePath
              chartPath: '$(Agent.BuildDirectory)/drop-operator/zeebe-operate-0.1.0.tgz'
              releaseName: '$(release_name)-operator'
              valueFile: '$(Agent.BuildDirectory)/drop-operator/values.default.yaml'
