apiVersion: v1
kind: Service
metadata:
  name: {{ include "zeebe-operate.fullname" . }}
  labels:
    app: {{ include "zeebe-operate.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    name: http
    targetPort: 8080
    protocol: TCP
  selector:
    app: {{ include "zeebe-operate.fullname" . }}

---
    
apiVersion: v1
kind: Service
metadata:
  name: operator-svc
#   annotations:
#     service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  ports:
  - name: proxy-port
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: zeebe-operator-zeebe-operate
  type: LoadBalancer
